name: Bug Report
description: File a bug report.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  As you fill in the details, here's a few things to consider:
        - Which version of libreswan?
          If possible, please try mainline.  Knowing it is still happening in the latest version is really helpful.
          If you require support for an old libreswan version, please see https://libreswan.org/wiki/Support
        - Is the peer running libreswan, or something else?
          Having access to the peer and its logs is often needed when diagnosing a problem.
        - IKEv1 or IKEv2?
          IKEv1 is obsolete; do you know if the problem happens with IKEv2?
        - ESP or AH?
          AH is obsolete; do you know if the problem happens with ESP using NULL authentication
        - VTI?
          VTI is obsolete; do you know if the problem happens with `ipsec-interface=` (XFRMI on Linux)
    validations:
      required: false
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what you expected to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Your configuration
      description: Please copy and past your configuration file.
      placeholder: |
        - this will be automatically formatted into code, so no need for backticks
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste the relevant log output
      placeholder: |
        - if necessary remove sensitive details
        - keep as much information as possible
        - there is no need to include debug output
          most problems are better understood with just the standard logs
        - this will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
