name: Bug Report
description: File a bug report.
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Your System details
      description: Please provide the output from `ipsec whack --version` and `uname -a`.  If the other end is different, please provide that as well.
    validations:
      required: true
  - type: checkboxes
    id: ike_version
    attributes:
      label: IKE Version
      options:
        - label: IKEv1
        - label: IKEv2 (if you can, please try reproducing the problem using IKEv2)
    validations:
      required: true
  - type: checkboxes
    id: protocol
    attributes:
      label: Protocol
      options:
        - label: ESP
        - label: AH (if you can, please try reproducing the problem using ESP and NULL authentication)
    validations:
      required: false
  - type: checkboxes
    id: interface
    attributes:
      label: IPsec or Virtual Interface?
      options:
        - label: IPsec Interface
        - label: VTI (if you can, please try reproducing the problem using `ipsec-interface=` and NULL authentication)
    validations:
      required: false
  - type: textarea
    attributes:
      label: What happened?
      description: Also tell us, what you expected to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Your configuration
      description: Please copy and past your configuration file.
      placeholder: |
        - if necessary remove sensitive details
          but keep as much information as possible
        - this will be automatically formatted into code, so no need for backticks
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste the relevant log output
      placeholder: |
        - if necessary remove sensitive details
          but keep as much information as possible
        - there is no need to include debug output
          most problems are better understood with just the standard logs
        - this will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
